# Generated by Django 4.2.7 on 2023-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=20, null=True)),
                ('peso', models.IntegerField(null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('alergia', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
