# Generated by Django 4.2.7 on 2023-12-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeros', '0002_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermero',
            name='dato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeros.datos'),
        ),
    ]
