# Generated by Django 4.2.7 on 2023-12-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeros', '0004_enfermero_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enfermero',
            name='antecedentes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeros.enfermedad'),
        ),
    ]
